"""50 curated personas for diverse synthetic data generation."""
from __future__ import annotations

from tessera.core.models import Persona

PERSONAS: list[Persona] = [
    # --- Formal / Expert ---
    Persona(
        name="Senior Software Engineer",
        formality="formal",
        expertise="expert",
        age_range="30-45",
        cultural_context="North American tech industry",
        writing_quirks=["uses technical jargon", "concise and precise", "bullet points"],
    ),
    Persona(
        name="Financial Analyst",
        formality="formal",
        expertise="expert",
        age_range="28-42",
        cultural_context="Corporate finance, Wall Street adjacent",
        writing_quirks=["references metrics", "uses financial terminology", "structured prose"],
    ),
    Persona(
        name="Legal Professional",
        formality="formal",
        expertise="expert",
        age_range="32-55",
        cultural_context="US legal system",
        writing_quirks=["precise language", "hedging phrases", "long sentences", "passive voice"],
    ),
    Persona(
        name="Academic Researcher",
        formality="formal",
        expertise="expert",
        age_range="28-50",
        cultural_context="University research environment",
        writing_quirks=["cites prior work", "hedges claims", "dense paragraphs", "Oxford commas"],
    ),
    Persona(
        name="Medical Doctor",
        formality="formal",
        expertise="expert",
        age_range="32-55",
        cultural_context="Clinical medicine, hospital setting",
        writing_quirks=["medical terminology", "brief and systematic", "avoids ambiguity"],
    ),
    # --- Semi-formal / Intermediate ---
    Persona(
        name="Product Manager",
        formality="semi-formal",
        expertise="intermediate",
        age_range="27-40",
        cultural_context="Silicon Valley startup culture",
        writing_quirks=["outcome-focused", "uses OKR/KPI language", "expressive punctuation"],
    ),
    Persona(
        name="Customer Success Representative",
        formality="semi-formal",
        expertise="intermediate",
        age_range="24-35",
        cultural_context="SaaS B2B company",
        writing_quirks=["warm and professional", "uses customer name", "action-oriented"],
    ),
    Persona(
        name="Small Business Owner",
        formality="semi-formal",
        expertise="intermediate",
        age_range="35-55",
        cultural_context="Main Street America, retail/service",
        writing_quirks=["direct and practical", "occasional typo", "no-nonsense"],
    ),
    Persona(
        name="HR Manager",
        formality="semi-formal",
        expertise="intermediate",
        age_range="30-48",
        cultural_context="Mid-size corporation",
        writing_quirks=["policy-minded", "inclusive language", "thorough"],
    ),
    Persona(
        name="Graduate Student",
        formality="semi-formal",
        expertise="intermediate",
        age_range="22-30",
        cultural_context="North American graduate school",
        writing_quirks=["eager and verbose", "uses hedging", "references coursework"],
    ),
    Persona(
        name="Freelance Designer",
        formality="semi-formal",
        expertise="intermediate",
        age_range="25-38",
        cultural_context="Creative industry, remote work",
        writing_quirks=["visual metaphors", "casual warmth", "expressive punctuation"],
    ),
    Persona(
        name="High School Teacher",
        formality="semi-formal",
        expertise="intermediate",
        age_range="26-50",
        cultural_context="Public school system",
        writing_quirks=["explanatory tone", "uses analogies", "patient phrasing"],
    ),
    Persona(
        name="Registered Nurse",
        formality="semi-formal",
        expertise="intermediate",
        age_range="26-45",
        cultural_context="Hospital or clinic setting",
        writing_quirks=["systematic", "acronym-heavy", "empathetic but efficient"],
    ),
    Persona(
        name="Real Estate Agent",
        formality="semi-formal",
        expertise="intermediate",
        age_range="30-52",
        cultural_context="US suburban real estate market",
        writing_quirks=["enthusiastic", "uses exclamation points", "market-focused language"],
    ),
    Persona(
        name="Accountant",
        formality="semi-formal",
        expertise="intermediate",
        age_range="28-50",
        cultural_context="Public accounting firm",
        writing_quirks=["numbers-first", "conservative tone", "thorough documentation"],
    ),
    # --- Casual / Novice ---
    Persona(
        name="College Student",
        formality="casual",
        expertise="novice",
        age_range="18-22",
        cultural_context="US undergraduate, campus life",
        writing_quirks=["informal language", "abbreviations", "occasional typo", "expressive punctuation"],
    ),
    Persona(
        name="Elderly Retiree",
        formality="casual",
        expertise="novice",
        age_range="65-80",
        cultural_context="US suburban retirement",
        writing_quirks=["polite phrasing", "full sentences", "may over-explain context", "formal greetings"],
    ),
    Persona(
        name="Teenager",
        formality="casual",
        expertise="novice",
        age_range="14-17",
        cultural_context="US high school, social media native",
        writing_quirks=["heavy slang", "lowercase", "minimal punctuation", "impatient tone"],
    ),
    Persona(
        name="Non-native Speaker (Intermediate)",
        formality="casual",
        expertise="novice",
        age_range="25-40",
        cultural_context="ESL learner, global background",
        writing_quirks=["occasional grammar errors", "direct phrasing", "missing articles"],
    ),
    Persona(
        name="Frustrated Customer",
        formality="casual",
        expertise="novice",
        age_range="30-55",
        cultural_context="Consumer complaint context",
        writing_quirks=["capitalized words for emphasis", "exclamation points", "restates problem repeatedly"],
    ),
    Persona(
        name="Enthusiastic New User",
        formality="casual",
        expertise="novice",
        age_range="20-35",
        cultural_context="Consumer tech adopter",
        writing_quirks=["lots of questions", "excited tone", "expressive punctuation", "overly detailed"],
    ),
    Persona(
        name="Busy Parent",
        formality="casual",
        expertise="novice",
        age_range="30-45",
        cultural_context="Suburban family, time-constrained",
        writing_quirks=["brief messages", "mid-sentence topic switches", "typos from mobile"],
    ),
    Persona(
        name="Tech-Averse User",
        formality="casual",
        expertise="none",
        age_range="50-70",
        cultural_context="Non-technical consumer",
        writing_quirks=["avoids jargon", "describes symptoms not causes", "unsure of terminology"],
    ),
    Persona(
        name="Overconfident Novice",
        formality="casual",
        expertise="novice",
        age_range="22-30",
        cultural_context="Self-taught, online community",
        writing_quirks=["states opinions as facts", "confident errors", "doesn't ask for clarification"],
    ),
    # --- Very casual ---
    Persona(
        name="Distracted Typer",
        formality="very_casual",
        expertise="novice",
        age_range="18-30",
        cultural_context="Mobile-first user",
        writing_quirks=["frequent typos", "autocorrect artifacts", "fragmented sentences", "no caps"],
    ),
    Persona(
        name="One-Line Responder",
        formality="very_casual",
        expertise="novice",
        age_range="16-28",
        cultural_context="Chat-native, minimal effort communicator",
        writing_quirks=["single sentence max", "no punctuation", "terse to the point of ambiguity"],
    ),
    # --- More intermediate ---
    Persona(
        name="IT Support Technician",
        formality="semi-formal",
        expertise="intermediate",
        age_range="24-40",
        cultural_context="Corporate IT helpdesk",
        writing_quirks=["troubleshooting language", "numbered steps", "asks clarifying questions"],
    ),
    Persona(
        name="Marketing Manager",
        formality="semi-formal",
        expertise="intermediate",
        age_range="27-42",
        cultural_context="B2C brand team",
        writing_quirks=["persuasive tone", "audience-first thinking", "brand voice conscious"],
    ),
    Persona(
        name="Operations Manager",
        formality="semi-formal",
        expertise="intermediate",
        age_range="32-50",
        cultural_context="Manufacturing or logistics company",
        writing_quirks=["process-oriented", "efficiency-focused", "direct requests"],
    ),
    Persona(
        name="Junior Developer",
        formality="semi-formal",
        expertise="novice",
        age_range="21-27",
        cultural_context="First job post-bootcamp or CS degree",
        writing_quirks=["asks many questions", "pastes code snippets", "uncertain tone"],
    ),
    Persona(
        name="Data Scientist",
        formality="semi-formal",
        expertise="expert",
        age_range="26-40",
        cultural_context="ML team at tech company",
        writing_quirks=["statistical framing", "caveats and confidence intervals", "notebook mindset"],
    ),
    Persona(
        name="Sales Representative",
        formality="semi-formal",
        expertise="intermediate",
        age_range="25-40",
        cultural_context="B2B software sales",
        writing_quirks=["value-proposition language", "prospect-centric", "follows up frequently"],
    ),
    Persona(
        name="Startup Founder",
        formality="semi-formal",
        expertise="intermediate",
        age_range="25-38",
        cultural_context="Early-stage tech startup",
        writing_quirks=["moves fast", "high-level thinking", "occasional buzzwords", "time-pressed"],
    ),
    Persona(
        name="Government Employee",
        formality="formal",
        expertise="intermediate",
        age_range="30-55",
        cultural_context="Federal or state bureaucracy",
        writing_quirks=["follows procedure", "references policy", "cautious language", "passive voice"],
    ),
    Persona(
        name="Journalist",
        formality="semi-formal",
        expertise="intermediate",
        age_range="25-45",
        cultural_context="Online news media",
        writing_quirks=["inverted pyramid structure", "attribution phrases", "active voice"],
    ),
    # --- International ---
    Persona(
        name="Non-native Speaker (Advanced)",
        formality="semi-formal",
        expertise="intermediate",
        age_range="28-45",
        cultural_context="European or Asian professional working in English",
        writing_quirks=["slightly formal register", "occasional unusual phrasing", "careful word choice"],
    ),
    Persona(
        name="Non-native Speaker (Basic)",
        formality="casual",
        expertise="novice",
        age_range="20-40",
        cultural_context="Recent immigrant or early ESL learner",
        writing_quirks=["simple vocabulary", "missing prepositions", "direct literal translation patterns"],
    ),
    Persona(
        name="British Professional",
        formality="formal",
        expertise="intermediate",
        age_range="30-50",
        cultural_context="UK corporate or civil service",
        writing_quirks=["British spellings", "understated tone", "polite indirectness", "dry humor"],
    ),
    Persona(
        name="Australian Casual",
        formality="casual",
        expertise="intermediate",
        age_range="22-40",
        cultural_context="Australia, informal work culture",
        writing_quirks=["colloquialisms", "self-deprecating humor", "direct but friendly", "shortened words"],
    ),
    Persona(
        name="Indian Professional",
        formality="semi-formal",
        expertise="intermediate",
        age_range="25-45",
        cultural_context="India tech or services industry",
        writing_quirks=["respectful tone", "slightly formal even in casual contexts", "reconfirms understanding"],
    ),
    # --- Edge cases ---
    Persona(
        name="Angry Customer",
        formality="very_casual",
        expertise="none",
        age_range="25-60",
        cultural_context="Consumer complaint, escalation context",
        writing_quirks=["all-caps words", "repetitive emphasis", "demands immediate action", "threatening tone"],
    ),
    Persona(
        name="Passive-Aggressive User",
        formality="casual",
        expertise="novice",
        age_range="28-45",
        cultural_context="Dissatisfied service customer",
        writing_quirks=["sarcasm", "eye-roll phrases", "complies while complaining", "quotes back policy sarcastically"],
    ),
    Persona(
        name="Verbose Explainer",
        formality="semi-formal",
        expertise="intermediate",
        age_range="35-55",
        cultural_context="Over-thorough communicator",
        writing_quirks=["provides unnecessary background", "parenthetical asides", "restates points multiple ways"],
    ),
    Persona(
        name="Ultra-Terse",
        formality="very_casual",
        expertise="intermediate",
        age_range="25-40",
        cultural_context="Minimal communication style",
        writing_quirks=["telegraphic sentences", "no pleasantries", "drops articles and pronouns"],
    ),
    Persona(
        name="Polite but Confused",
        formality="casual",
        expertise="none",
        age_range="40-65",
        cultural_context="Non-technical consumer unsure of process",
        writing_quirks=["apologizes frequently", "asks same question multiple ways", "thanks repeatedly"],
    ),
    Persona(
        name="Power User",
        formality="semi-formal",
        expertise="expert",
        age_range="25-40",
        cultural_context="Heavy software tool user, developer adjacent",
        writing_quirks=["keyboard shortcut references", "feature requests", "bug reports", "edge case focus"],
    ),
    Persona(
        name="New Hire",
        formality="semi-formal",
        expertise="novice",
        age_range="21-30",
        cultural_context="First weeks at a new job",
        writing_quirks=["eager to impress", "follows instructions literally", "asks permission before acting"],
    ),
    Persona(
        name="Risk-Averse Professional",
        formality="formal",
        expertise="intermediate",
        age_range="35-55",
        cultural_context="Compliance or audit function",
        writing_quirks=["qualifies every statement", "seeks written confirmation", "references risk frameworks"],
    ),
    Persona(
        name="Creative Writer",
        formality="casual",
        expertise="intermediate",
        age_range="22-40",
        cultural_context="Fiction or content writing community",
        writing_quirks=["evocative language", "metaphors", "stream-of-consciousness at times", "unusual punctuation"],
    ),
    Persona(
        name="Serial Complainer",
        formality="casual",
        expertise="novice",
        age_range="35-65",
        cultural_context="Repeat support ticket filer",
        writing_quirks=["references prior complaints", "escalation threats", "demands compensation", "detailed grievance lists"],
    ),
]


def get_all_personas() -> list[Persona]:
    return PERSONAS


def get_personas_by_formality(formality: str) -> list[Persona]:
    return [p for p in PERSONAS if p.formality == formality]


def get_personas_by_expertise(expertise: str) -> list[Persona]:
    return [p for p in PERSONAS if p.expertise == expertise]
