"""
RAG Evaluation — tests a model's ability to answer questions grounded in context.

This script simulates a RAG reader: given (context, question) pairs generated by
Tessera, it prompts gpt-4o-mini and scores the responses by question type.

Metrics reported:
  factoid      — token-level F1 (exact span retrieval)
  multi-hop    — token-level F1 (reasoning across two facts)
  unanswerable — accuracy (did the model correctly refuse to hallucinate?)

Usage:
    python examples/evaluate_rag.py
    python examples/evaluate_rag.py --input outputs/rag_eval_qa.jsonl --model gpt-4o-mini
"""
from __future__ import annotations

import argparse
import json
import os
import re
from collections import Counter
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv(Path(__file__).parent.parent / ".env")

# Keywords that indicate a correct refusal to answer (fuzzy match)
_UNANSWERABLE_SIGNALS = [
    "cannot be determined",
    "can't be determined",
    "not mentioned",
    "not provided",
    "not stated",
    "not specified",
    "does not provide",
    "doesn't provide",
    "no information",
    "not enough information",
    "insufficient information",
    "not found in",
    "not available in",
    "context does not",
    "context doesn't",
    "cannot answer",
    "unable to determine",
]

SYSTEM_PROMPT = (
    "You are a precise question-answering assistant. "
    "Answer the question based ONLY on the provided context. "
    "Do not use any outside knowledge. "
    "If the answer cannot be determined from the context alone, respond with exactly: "
    "This cannot be determined from the provided context. "
    "Keep answers concise — one sentence or less for factual questions."
)


# ---------------------------------------------------------------------------
# Scoring helpers
# ---------------------------------------------------------------------------


def normalize(text: str) -> str:
    text = text.lower()
    text = re.sub(r"\b(a|an|the)\b", " ", text)
    text = re.sub(r"[^a-z0-9 ]", "", text)
    return " ".join(text.split())


def token_f1(pred: str, gold: str) -> float:
    pred_tokens = normalize(pred).split()
    gold_tokens = normalize(gold).split()
    if not pred_tokens or not gold_tokens:
        return 0.0
    common = Counter(pred_tokens) & Counter(gold_tokens)
    num_same = sum(common.values())
    if num_same == 0:
        return 0.0
    precision = num_same / len(pred_tokens)
    recall = num_same / len(gold_tokens)
    return 2 * precision * recall / (precision + recall)


def factoid_score(pred: str, gold: str) -> float:
    """Score a factoid answer.

    Full credit (1.0) if the normalized gold answer is a substring of the
    normalized prediction — handles the common case where the model wraps a
    correct short answer in a full sentence.  Falls back to token F1 when
    the gold answer is not found verbatim.
    """
    pred_norm = normalize(pred)
    gold_norm = normalize(gold)
    if gold_norm and gold_norm in pred_norm:
        return 1.0
    return token_f1(pred, gold)


def unanswerable_correct(pred: str) -> bool:
    pred_lower = pred.lower()
    return any(signal in pred_lower for signal in _UNANSWERABLE_SIGNALS)


# ---------------------------------------------------------------------------
# Main evaluation loop
# ---------------------------------------------------------------------------


def evaluate(input_path: str, model: str) -> None:
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    examples = []
    with open(input_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))

    if not examples:
        print(f"No examples found in {input_path}")
        return

    print("=" * 60)
    print(f"Tessera RAG Evaluation")
    print(f"Dataset:  {input_path}")
    print(f"Model:    {model}")
    print(f"Examples: {len(examples)}")
    print("=" * 60)

    scores: dict[str, list[float]] = {}
    errors = 0

    for i, ex in enumerate(examples, 1):
        qt = ex.get("question_type", "unknown")
        context = ex.get("context", "")
        question = ex.get("question", "")
        gold = ex.get("answer", "")

        try:
            resp = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
                ],
                temperature=0,
                max_tokens=200,
            )
            pred = resp.choices[0].message.content.strip()
        except Exception as exc:
            print(f"  [error] example {i}: {exc}")
            errors += 1
            continue

        if qt == "unanswerable":
            score = 1.0 if unanswerable_correct(pred) else 0.0
        elif qt == "factoid":
            score = factoid_score(pred, gold)
        else:
            score = token_f1(pred, gold)

        scores.setdefault(qt, []).append(score)

        if i % 10 == 0:
            print(f"  [{i}/{len(examples)}] evaluated...")

    # ---------------------------------------------------------------------------
    # Results
    # ---------------------------------------------------------------------------

    print(f"\n{'=' * 60}")
    print("RESULTS")
    print(f"{'=' * 60}")

    type_labels = {
        "factoid":      "Factoid F1          (direct extraction)",
        "multi-hop":    "Multi-hop F1        (cross-fact reasoning)",
        "unanswerable": "Unanswerable acc.   (hallucination refusal)",
        "abstractive":  "Abstractive F1      (synthesis / paraphrase)",
    }

    overall_scores: list[float] = []
    for qt in ["factoid", "multi-hop", "unanswerable", "abstractive"]:
        if qt not in scores:
            continue
        avg = sum(scores[qt]) / len(scores[qt])
        overall_scores.extend(scores[qt])
        label = type_labels.get(qt, qt)
        bar = "█" * int(avg * 20)
        print(f"  {label:<42} {avg:.3f}  {bar}")

    if overall_scores:
        overall = sum(overall_scores) / len(overall_scores)
        print(f"\n  {'Overall (mean across types)':<42} {overall:.3f}")

    print(f"\n  Examples evaluated: {len(examples) - errors}")
    if errors:
        print(f"  API errors:         {errors}")

    print()

    # Unanswerable-specific callout (most important for enterprise)
    if "unanswerable" in scores:
        ua_acc = sum(scores["unanswerable"]) / len(scores["unanswerable"])
        if ua_acc >= 0.85:
            print(f"  ✓ Hallucination refusal rate: {ua_acc:.1%} — strong (≥85%)")
        elif ua_acc >= 0.70:
            print(f"  ~ Hallucination refusal rate: {ua_acc:.1%} — acceptable (70–85%)")
        else:
            print(f"  ✗ Hallucination refusal rate: {ua_acc:.1%} — needs improvement (<70%)")
        print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a RAG reader on Tessera QA data.")
    parser.add_argument(
        "--input",
        default="outputs/rag_eval_qa.jsonl",
        help="Path to Tessera QA JSONL file (default: outputs/rag_eval_qa.jsonl)",
    )
    parser.add_argument(
        "--model",
        default=os.environ.get("TESSERA_DEFAULT_MODEL", "gpt-4o-mini"),
        help="OpenAI model to use as the RAG reader (default: gpt-4o-mini)",
    )
    args = parser.parse_args()
    evaluate(args.input, args.model)


if __name__ == "__main__":
    main()
